In [ ]:
# when  you combine multiple series its become dataframe

In [2]:
import numpy as np
import pandas as pd

In [3]:
# creating a data frame

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
columns=("name","age","city","salary")
df2=pd.DataFrame(data_list,columns=columns)

In [7]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
# Selection and Indexing og columns

In [9]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df2[['name','age']]

    name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [11]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
df2["designation"]=["drug dealer","smuggler","comedian","standup"]

In [13]:
df2

    name  age      city  salary  designation
0   John   28  New York   65000  drug dealer
1   Anna   34     Paris   70000     smuggler
2  Peter   29    Berlin   62000     comedian
3  Linda   42    London   85000      standup

In [14]:
# removing column

In [15]:
df2.drop("designation",axis=1,inplace=True)
# for removing it permanatly

In [16]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df2.drop(["name","city"],axis=1)
# showing the preview of after deleting the data not permenatly

   age  salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

In [18]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df2.drop(0,axis=0)

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [20]:
# Selecting Rows

In [21]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df2.loc[[0,1]]

   name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [23]:
# Selecting subsets of rows and columns

In [24]:
df2.loc[[0,1]] [["city","salary"]]

       city  salary
0  New York   65000
1     Paris   70000

In [25]:
df2.loc[[2,3]] [["name","age"]]

    name  age
2  Peter   29
3  Linda   42

In [26]:
# conditional selection

In [27]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# i only want to see those people whose age is above 30

In [32]:
df2[df2["age"]>30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [33]:
# I only people whose age is above 30 and their city must be paris

In [35]:
df2[(df2["age"]>30) & (df2["city"]=='paris')]

Empty DataFrame
Columns: [name, age, city, salary]
Index: []